version: '3.9'

services:
    filebrowser:
        image: hurlenko/filebrowser
        container_name: filebrowser
        ports:
            - 8082:8080
        volumes:
            - /home/pinouser:/data
            - /home/pinouser/docker/filebrowser/config:/config
        environment:
            - FB_BASEURL=/filebrowser
        restart: always
        networks:
            - default

networks:
    default:
        name: proxy_network
        external: true
