version: '3.8'

services:
    cache:
        image: redis:6.2-alpine
        restart: always
        ports:
            - '6379:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        env_file:
            - stack.env
        volumes:
            - cache:/data
        networks:
            - default
volumes:
    cache:
        driver: local

networks:
    default:
        name: traefik_network
        external: true
